var quotes = [

    ["I'm gonna make him an offer he can't refuse", "The Godfather"],
["May the force be with you", "Star Wars"],
["Go ahead, make my day", "Sudden Impact"],
["I do wish we could chat longer, but... I'm having an old friend for dinner", "Silence of the Lambs"],
    
["The truth? You can't handle the truth!", "A Few Good Men"],
["Mama always said life was like a box of chocolates. You never know what you're gonna get", "Forrest Gump"],
["Heeeere's Johnny!", "The Shining"],
["Say hello to my little friend!", "Scarface"],
["If you have a milkshake, and I have a milkshake, and I have a straw. And my straw reaches, acrooooss the room, and starts to drink your milkshake. I! Drink! Your! milkshake! I drink it up!", "There Will Be Blood"],
["I love the smell of napalm in the morning", "Apocalypse Now"],
["You talkin' to me?", "Taxi Driver"],
["Yippee kay-ay motherfucker", "Die Hard"],
["And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy my brothers. And you will know my name is the Lord when I lay my vengeance upon thee", "Pulp Fiction"],
["Houston, we have problem", "Apollo 13"],
["Let me tell you this, the older you do get the more rules they're gonna try to get you to follow. You just gotta keep livin' man, L-I-V-I-N.", "Dazed and Confused"],
["What's in the box?!!", "Se7en"],
["Keep your friends close but your enemies closer.", "The Godfather II"],
["The greatest trick the Devil ever pulled was convincing the world he didn't exist. And like that, poof. He's gone", "The Usual Suspects"],
["Greed, for lack of a better word, is good", "Wall Street"],
["Show me the money!", "Jerry Maguire"],
["Yes they deserve to die and I hope they burn in hell!!", "A Time to Kill"],
["What's the most you ever lost on a coin toss?", "No Country For Old Men"],
["Juuuuust a bit outside", "Major League"],
["You're going to need a bigger boat", "Jaws"],
["I have had it with these motherfuckin' snakes on this motherfuckin' plane!", "Snakes on a Plane"],
["If you build it, he will come", "Field of Dreams"],
["I guess it comes down to one choice really.  Get busy livin' or get busy dyin'", "The Shawshank Redemption"],
["Are you not entertained?!!", "Gladiator"],
["Heineken?!! Fuck that shit.  Pabst Blue Ribbon!", "Blue Velvet"],
["It's not your fault.", "Good Will Hunting"],
["Roads? Where we're going we don't need roads.", "Back to the Future"],
["I'm funny how, I mean funny like I'm a clown, I amuse you? I make you laugh, I'm here to fuckin' amuse you? What do you mean funny, funny how? How am I funny?", "Goodfellas"],
["Attica! Attica!", "Dog Day Afternoon"],
["I'm the king of the world!", "Titanic"],
["King Kong ain't got shit on me!", "Training Day"],
["I wanted to see exotic Vietnam... the crown jewel of Southeast Asia. I wanted to meet interesting and stimulating people of an ancient culture... and kill them", "Full Metal Jacket"],
["This is your life and it's ending one minute at a time.", "Fight Club"],
["When I was your age they would say we can become cops, or criminals. Today, what I'm saying to you is this: when you're facing a loaded gun, what's the difference?", "The Departed"],
["He's not the Messiah.  He's a very naughty boy!", "Life of Brian"],
["Warriooors. Come out and plaaaay", "Warriors"],
["Ventura! - Yes, Satan? *turns around* Oh I'm sorry sir, you sounded like someone else", "Ace Ventura"],
["Now. Where was I?", "Memento"],
["Just when I thought you couldn't possibly be any dumber, you go and do something like this... and totally redeem yourself!", "Dumb and Dumber"],
["Just when I thought I was out, they pull me back in", "The Godfather III"],
["I told that Kraut a fuckin thousand times, I don't roll on shabbos!!", "The Big Lebowski"],
["There's no crying in baseball!", "A League of Their Own"],
["I've seen things you people wouldn't believe. Attack ships on fire off the shoulder of Orion. I watched C-beams glitter in the dark near the Tannhäuser Gate. All those moments will be lost in time, like tears in rain... Time to die", "Blade Runner"],
["Pop quiz, hotshot. There's a bomb on a bus. Once the bus goes 50 miles an hour, the bomb is armed. If it drops below 50, it blows up. What do you do? What do you do?", "Speed"],
["I don't know how to put this, but I'm kind of a big deal...people know me...I'm very important.  I have many leather-bound books and my apartment smells of rich mahogany", "Anchorman: The Legend of Ron Burgundy"],
["Do you like scary movies?", "Scream"],
["Jam: It's a teenage girl walking along the side of the highway. I mean, they, they, they make scary movies that start out like that. Trip: Hey, but, but they make porno movies that start out like that too, man!", "Detroit Rock City"],
["You don't understand. I coulda had class. I coulda been a contender. I coulda been somebody, instead of a bum, which is what I am", "On the Waterfront"],
["You're tearing me apart! You, you say one thing, and he says another, and then everybody changes back again!", "Rebel Without a Cause"],
["Life moves pretty fast. You don't stop and look around once in a while, you could miss it", "Ferris Bueller's Day Off"],
["We have an old saying in Delta House: don't get mad, get even", "Animal House"],
["I chose not to choose life. I chose somethin' else. And the reasons? There are no reasons. Who needs reasons when you've got heroin?","Trainspotting"],
["You have smoked yourself retarded", "Half Baked"],
["I wish I knew how to quit you", "Brokeback Mountain"],
["Surely you can't be serious? - I am serious.  And don't call me Shirley", "Airplane!"],
["It's good to be the king", "History of the World: Part 1"],
["My name is Inigo Montoya. You killed my father.  Prepare to die", "The Princess Bride"],
["Do I make you horny baby? Do I make you randy?", "Austin Powers: The Spy Who Shagged Me"],
["That's right. I've killed women and children. I've killed just about everything that walks or crawled at one time or another. And I'm here to kill you, Little Bill, for what you did to Ned.", "Unforgiven"],
["I am a golden god!", "Almost Famous"],
["I'm sorry WIlson!", "Cast Away"],
["It's like a warm apple pie..", "American Pie"],
["Bring out your dead", "Monty Python and the Holy Grail"],
["Excuse me while I whip this out", "Blazing Saddles"],
["Well, my compliment to you is, the next morning, I started taking the pills. - I don't quite get how that's a compliment for me. - You make me want to be a better man. - That's maybe the best compliment of my life", "Doc Martin"],
["It's too late, Alva", "Vampire's Kiss"],
["Just when I thought you couldn't possibly be any dumber, you go and do something like this...and totally redeem yourself!", "Dumb and Dumber"],
["I have nipples, Greg, could you milk me?", "Meet the Parents"],
["Nobody puts baby in a corner.", "Dirty Dancing"],
["Cinderella story.  Outta nowhere.  A groundskeeper, now about to become the Master's champion.  It looks like a mirac...It's in the hole! It's in the hole! It's in the hole!", "Caddyshack"],
["We're on a mission from God", "The Blues Brothers"],
["We had two bags of grass, seventy-five pellets of mescaline, five sheets of high-powered blotter acid, a saltshaker half-full of cocaine, and a whole galaxy of multi-colored uppers, downers, screamers, laughers... Also, a quart of tequila, a quart of rum, a case of beer, a pint of raw ether, and two dozen amyls. Not that we needed all that for the trip, but once you get locked into a serious drug collection, the tendency is to push it as far as you can", "Fear and Loathing in Las Vegas"],
["We came, we saw, we kicked it's ass", "Ghostbusters"],
["You drop a pass, you run a mile. You miss a blocking assignment, you run a mile. You fumble the football, and i will break my foot off in your John Brown hind parts and then you will run a mile. Perfection. Let's go to work", "Remember the Titans"],
["Free your mind, your ass will follow. - Platoon"],
["Mr. Madison, what you've just said is one of the most insanely idiotic things I have ever heard. At no point in your rambling, incoherent response were you even close to anything that could be considered a rational thought. Everyone in this room is now dumber for having listened to it. I award you no points, and may God have mercy on your soul", "Billy Madison"],
["Excuse me, I believe you have my stapler.", "Office Space"],
["So, I want you to get up now. I want all of you to get up out of your chairs. I want you to get up right now and go to the window. Open it, and stick your head out, and yell: I'M AS MAD AS HELL, AND I'M NOT GOING TO TAKE THIS ANYMORE!", "Network"],
["What we've got here is failure to communicate. Some men you just can't reach. So you get what we had here last week, which is the way he wants it. Well, he gets it. I don't like it any more than you men", "Cool Hand Luke"],
["Come out, come out, wherever you are!", "Cape Fear"],
["I know it's pretty baby, but I didn't take it out for air", "Requiem For A Dream"],
["If you're gonna spew, spew into this", "Wayne's World"],
["He may have advanced delusionary schizophrenia with involuntary narcissistic rage.  But he is a very gentle person!", "Me, Myself, and Irene"],
["This guy ain't a gangster, his real name's Clarence.", "8 Mile"],
["Never underestimate the power of denial", "American Beauty"]

    
]


function newQuote() {
    var randomNumber = Math.floor(Math.random() * (quotes.length));
    document.getElementById('quoteDisplay').innerHTML = '<h1>' + quotes[randomNumber][0] + '</h1>';
    document.getElementById('movieDisplay').innerHTML = '<h3>' + quotes[randomNumber][1] + '</h3>';
}
